//
//  RealmManager.swift
//  iSignIn
//
//  Created by Dmitrij on 2023-01-03.
//

import Foundation
import RealmSwift

class RealmManager {
    
    static let shared = RealmManager()
    
    private init () {
        
    }
    
    private var _realm: Realm?
    private var _realmConfiguration: Realm.Configuration {
        var config = Realm.Configuration.defaultConfiguration
        config.schemaVersion = 1
        return config
    }
    
    func getMainRealm () -> Realm? {
        guard let realm = _realm else {
            _realm = try? Realm(configuration: _realmConfiguration)
            
            return _realm
        }
        
        return realm
    }
    
    func getBackgroundRealm () -> Realm? {

        let realm = try? Realm(configuration: _realmConfiguration)
        
        return realm
    }
    
    func getAttendeesToSubmit (program: Program?) -> [Attendee] {
        
        if let program = program {
            return program.getAttendeesToSubmit()
        }
        else {
            let realm = getBackgroundRealm()
            //[.readySigned, .readyNoShow].contains(attendee.submitStatus)  && !attendee.submitSubmited
            if let objects = realm?.objects(Attendee.self).filter("(submitStatus == %@ or submitStatus == %@) and submitSubmited == %@", Attendee.AttendeeSubmitStatus.readySigned, Attendee.AttendeeSubmitStatus.readyNoShow, false) {
                return Array(objects)
            }
            return [Attendee]()
        }
    }
    
    func getStateList () -> [String] {
        let stateList =  ["AK","AZ","AR","CA","CO","CT","DE","FL","GA","HI","ID","IL","IN",
                                "IA","KS","KY","LA","ME","MD","MA","MI","MN", "MS","MO","MT", "NE", "NV", "NH",
                                "NJ", "NM", "NY", "NC", "ND", "OH","OK","OR","PA","PR","RI","SC","SD","TN", "TX","UT","VT",
                                "VA","WA","WV", "WI", "WY"]
        return stateList
    }
    
    func getSpecialityList () -> [String] {
        let specialtyList = [ "Allergy And Immunology",
                              "Emergency Medicine",
                              "Endocrinology",
                              "Endocrinology & Metabolism",
                              "Family Medicine",
                              "General Practice",
                              "Infectious Diseases",
                              "Internal Medicine",
                                     "Nephrology",
                                     "Nurse Practitioner",
                                     "Ophthalmology",
                                     "OPTOMETRIST",
                                     "Orthopedic Surgery",
                                     "Pain Management",
                                     "Pediatrics",
                                     "Pharmacist",
                                     "Physical Medicine & Rehabilitation",
                                     "Physician Assistant",
                                     "PODIATRIST",
                                     "Primary Care",
                                     "Registered Nurse",
                                     "Rheumatology",
                                     
                                     "Abdominal Radiology",
                                     "Abdominal Surgery",
                                     "Addiction Medicine",
                                     "Addiction Psychiatry",
                                     "Addiction Psychiatry - Registered N",
                                     "Adolescent Medicine",
                                     "Adolescent Medicine - Family Medici",
                                     "Adolescent Medicine - Pediatrics",
                                     "Adolescent Medicine (Internal Medic",
                                     "Adult Cardiothoracic Anesthesiology",
                                     "Adult Health",
                                     "Advanced Practice Registered Nurse",
                                     "Aerospace Medicine",
                                     "Allergy",
                                     "Allergy/Immunology, Diag Lab Immuno",
                                     "Anatomic Pathology",
                                     "Anesthesiology",
                                     "Anesthesiology - Advanced Practice ",
                                     "Anesthesiology - Physician Assistan",
                                     "Anesthesiology, Critical Care Medic",
                                     "Anesthesiology, Pain Medicine",
                                     "Behavioral Health",
                                     "Cardiology",
                                     "Cardiothoracic Radiology",
                                     "Cardiothoracic Surgery",
                                     "Cardiovascular Disease - Registered",
                                     "Cardiovascular Disease - Technician",
                                     "Cardiovascular Diseases",
                                     "Cardiovascular Surgery",
                                     "Child Abuse Pediatrics - Pediatrics",
                                     "Child And Adolescent Psychiatry",
                                     "Child And Adolescent Psychiatry - A",
                                     "Child And Adolescent Psychiatry - R",
                                     "Child Neurology",
                                     "Child Psychiatry",
                                     "Chiropractic",
                                     "Clinical Biochemical Genetics",
                                     "Clinical Cardiac Electrophysiology ",
                                     "Clinical Child And Adolescent Psych",
                                     "Clinical Cytogenetics",
                                     "Clinical Genetics",
                                     "Clinical Health Psychology - Psycho",
                                     "Clinical Molecular Genetics",
                                     "Clinical Neurophysiology - Neurolog",
                                     "Clinical Nurse Specialist",
                                     "Clinical Pathology",
                                     "Clinical Pharmacology - Other",
                                     "Clinical Psychology - Psychology",
                                     "Cognitive And Behavioral Psychology",
                                     "Colon And Rectal Surgery",
                                     "Congenital Cardiac Surgery",
                                     "Cosmetic Surgery",
                                     "Counseling Psychology - Psychology",
                                     "Counselor - Behavioral Health",
                                     "Couple And Family Psychology - Psyc",
                                     "Critical Care Medicine",
                                     "Critical Care Medicine - Advanced P",
                                     "Critical Care Medicine - Registered",
                                     "Critical Care Surgery",
                                     "Dentist",
                                     "Dentist Other Specialty",
                                     "Dermatologic Surgery",
                                     "Dermatological Diag Lab Immunology",
                                     "Dermatology",
                                     "Dermatology - Physician Assistant",
                                     "Dermatopathology",
                                     "Developmental-Behavioral Pediatrics",
                                     "Diabetes",
                                     "Diabetology",
                                     "Diabetology - Registered Nurse",
                                     "Diagnostic Radiology",
                                     "Emergency Medicine - Advanced Pract",
                                     "Emergency Medicine - Physician Assi",
                                     "Emergency Medicine - Registered Nur",
                                     "Emergency Medicine, Sports Medicine",
                                     "Endodontics",
                                     "Endovascular Surgical Neuroradiolog",
                                     "Epidemiology",
                                     "Facial Plastic Surgery, Otolaryngol",
                                     "Family Medicine - Advanced Practice",
                                     "Family Medicine - Physician Assista",
                                     "Family Practice",
                                     "Family Practice, Geriatric Medicine",
                                     "Family Practice, Sports Medicine",
                                     "Family Practice/Psychiatry",
                                     "Female Pelvic Medicine And Reconstr",
                                     "Flexible Specialty (Residents Only)",
                                     "Foot Surgery - Podiatry",
                                     "Forensic Pathology",
                                     "Forensic Psychiatry",
                                     "Forensic Psychology - Psychology",
                                     "Gastroenterology",
                                     "Gastroenterology - Internal Medicin",
                                     "Gastroenterology - Registered Nurse",
                                     "General Practice - Advanced Practic",
                                     "General Practice - Registered Nurse",
                                     "General Preventive Medicine",
                                     "General Surgery",
                                     "Geriatric Medicine",
                                     "Geriatric Medicine - Advanced Pract",
                                     "Geriatric Medicine - Registered Nur",
                                     "Geriatric Psychiatry",
                                     "Geriatric Psychiatry - Advanced Pra",
                                     "Gerontology",
                                     "Geropsychology - Psychology",
                                     "Gynecological Oncology",
                                     "Gynecology",
                                     "Hand Surgery, Orthopedic Surgery",
                                     "Hand Surgery, Plastic Surgery",
                                     "Head And Neck Surgery",
                                     "Hematology",
                                     "Hematology - Internal Medicine",
                                     "Hematology/Oncology",
                                     "Hematology/Oncology - Internal Medi",
                                     "Hepatology",
                                     "Holistic Health",
                                     "Hospice And Palliative Medicine",
                                     "Hospice And Palliative Medicine - E",
                                     "Hospice And Palliative Medicine - P",
                                     "Hospice And Palliative Medicine - R",
                                     "Hospice And Palliative Medicine - S",
                                     "Hospice Palliative Medicine",
                                     "Hospitalist",
                                     "Hospitalist - Internal Medicine",
                                     "Immunology",
                                     "Infectious Disease - Internal Medic",
                                     "Infectious Disease - Registered Nur",
                                     "Internal Med, Card. Electrophysiolo",
                                     "Internal Medicine - Critical Care M",
                                     "Internal Medicine - Registered Nurs",
                                     "Internal Medicine, Diag Lab Immunol",
                                     "Internal Medicine, Geriatrics",
                                     "Internal Medicine, Sports Medicine",
                                     "Internal Medicine/Dermatology",
                                     "Internal Medicine/Emergency Medicin",
                                     "Internal Medicine/Neurology",
                                     "Internal Medicine/Pediatrics",
                                     "Internal Medicine/Physical Medicine",
                                     "Internal Medicine/Preventive Medici",
                                     "Internal Medicine/Psychiatry",
                                     "Interventional Cardiology - Interna",
                                     "Legal Medicine",
                                     "Maternal And Fetal Medicine",
                                     "Maternal And Fetal Medicine - Obste",
                                     "Medical Genetics",
                                     "Medical Management",
                                     "Medical Microbiology",
                                     "Medical Oncology - Advanced Practic",
                                     "Medical Oncology - Internal Medicin",
                                     "Medical Oncology - Pharmacist",
                                     "Medical Oncology - Registered Nurse",
                                     "Medical Toxicology (Em)",
                                     "Medical Toxicology (Preventative Me",
                                     "Medical Toxicology/Pediatrics",
                                     "Molecular Genetic Pathology",
                                     "Musculoskeletal Radiology",
                                     "Neonatal-Perinatal Medicine",
                                     "Neonatal-Perinatal Medicine - Advan",
                                     "Neonatal-Perinatal Medicine - Pedia",
                                     "Neonatal-Perinatal Medicine - Regis",
                                     "Nephrology - Internal Medicine",
                                     "Nephrology - Registered Nurse",
                                     "Neurodevelopmental Disabilities",
                                     "Neurodevelopmental Disabilities - P",
                                     "Neurological Surgery",
                                     "Neurological Surgery - Physician As",
                                     "Neurological Surgery, Critical Care",
                                     "Neurology",
                                     "Neurology - Advanced Practice Regis",
                                     "Neurology - Registered Nurse",
                                     "Neurology/Diagnostic Radiology/Neur",
                                     "Neuromuscular Medicine - Neurology",
                                     "Neuromuscular Medicine - Physical M",
                                     "Neurophysiology, Clin.",
                                     "Neuroradiology",
                                     "Neuroscience",
                                     "Nonpracticing Dentist",
                                     "Nuclear Cardiology",
                                     "Nuclear Medicine",
                                     "Nuclear Radiology",
                                     "Nuclear Radiology - Radiology",
                                     "Nurse Anesthetist",
                                     "Nutrition",
                                     "Nutrition - Registered Nurse",
                                     "Obstetrics",
                                     "Obstetrics - Registered Nurse",
                                     "Obstetrics And Gynecology",
                                     "Obstetrics And Gynecology - Advance",
                                     "Obstetrics/Gynecology, Critical Car",
                                     "Occupational Medicine",
                                     "Oncology",
                                     "Oncology Medical",
                                     "Ophthalmology - Registered Nurse",
                                     "Ophthalmology/Peds",
                                     "Oral And Maxillofacial Pathology",
                                     "Oral And Maxillofacial Surgery",
                                     "Oral Surgery",
                                     "Orthodontics And Dentofacial Orthop",
                                     "Orthopaedic Surgery - Physician Ass",
                                     "Orthopaedic Surgery - Registered Nu",
                                     "Orthopedic Surg, Adult Reconstructi",
                                     "Orthopedic Surg, Musculoskeletal On",
                                     "Orthopedic Surg, Pediatric Orthoped",
                                     "Orthopedic Surg, Sports Medicine",
                                     "Orthopedic Surg, Trauma",
                                     "Orthopedic Surgery Of The Spine",
                                     "Orthopedics",
                                     "Orthopedics, Foot And Ankle",
                                     "Osteopathic Manipulative Medicine",
                                     "Otolaryngology",
                                     "Otolaryngology - Registered Nurse",
                                     "Pain Medicine",
                                     "Pain Medicine - Neurology",
                                     "Pain Medicine - Other",
                                     "Pain Medicine - Physical Medicine A",
                                     "Pain Medicine - Psychiatry",
                                     "Pain Medicine - Registered Nurse",
                                     "Palliative Medicine",
                                     "Palliative Medicine - Advanced Prac",
                                     "Pathology",
                                     "Pathology - Molecular Genetic",
                                     "Pathology, Anatomic/Clinical",
                                     "Pathology, Blood Banking",
                                     "Pathology, Chemical",
                                     "Pathology, Cytopathology",
                                     "Pathology, Hematology",
                                     "Pathology, Neuropathology",
                                     "Pathology, Pediatric Pathology",
                                     "Pediatric Allergy",
                                     "Pediatric Anesthesiology - Anesthes",
                                     "Pediatric Cardiology",
                                     "Pediatric Critical Care Medicine",
                                     "Pediatric Critical Care Medicine - ",
                                     "Pediatric Dentistry",
                                     "Pediatric Diagnostic Lab Immunology",
                                     "Pediatric Emergency Medicine",
                                     "Pediatric Emergency Medicine (Emerg",
                                     "Pediatric Endocrinology",
                                     "Pediatric Gastroenterology",
                                     "Pediatric Hematology Oncology",
                                     "Pediatric Hematology-Oncology - Adv",
                                     "Pediatric Hematology-Oncology - Ped",
                                     "Pediatric Hematology-Oncology - Reg",
                                     "Pediatric Infectious Diseases",
                                     "Pediatric Infectious Diseases - Ped",
                                     "Pediatric Nephrology",
                                     "Pediatric Neurological Surgery",
                                     "Pediatric Neurology - Neurology",
                                     "Pediatric Ophthalmology - Pediatric",
                                     "Pediatric Otolaryngology",
                                     "Pediatric Pulmonology",
                                     "Pediatric Radiology",
                                     "Pediatric Rehabilitation Medicine -",
                                     "Pediatric Rheumatology",
                                     "Pediatric Sports Medicine",
                                     "Pediatric Surgery",
                                     "Pediatric Thoracic And Cardiac Surg",
                                     "Pediatric Transplant Hepatology",
                                     "Pediatric Urology",
                                     "Pediatrics - Advanced Practice Regi",
                                     "Pediatrics - Optometry",
                                     "Pediatrics - Physician Assistant",
                                     "Pediatrics - Registered Nurse",
                                     "Pediatrics Dermatology",
                                     "Pediatrics, Critical Care",
                                     "Pediatrics/Emergency Medicine",
                                     "Pediatrics/Medical Genetics",
                                     "Pediatrics/Physical Medicine & Reha",
                                     "Pediatrics/Physical Medicine And Re",
                                     "Pediatrics/Psychiatry/Child Psychia",
                                     "Periodontics",
                                     "Pharmacology",
                                     "Phlebology",
                                     "Physical Medicine And Rehabilitatio",
                                     "Physical Therapy - Assistant",
                                     "Plastic Surgery",
                                     "Plastic Surgery - Registered Nurse",
                                     "Plastic Surgery Within The Head And",
                                     "Proctology",
                                     "Prosthodontics",
                                     "Psych/Mental Health, Adult",
                                     "Psych/Mental Health, Child And Fami",
                                     "Psych/Mental Health, Chronically Il",
                                     "Psych/Mental Health, Community",
                                     "Psych/Mental Health, Geropsychiatri",
                                     "Psychiatry",
                                     "Psychiatry - Advanced Practice Regi",
                                     "Psychiatry - Registered Nurse",
                                     "Psychiatry/Neurology",
                                     "Psychiatry/Neurology - Combined Res",
                                     "Psychoanalysis",
                                     "Psychology",
                                     "Psychosomatic Medicine",
                                     "Public Health",
                                     "Public Health And General Preventiv",
                                     "Pulmonary Critical Care Medicine",
                                     "Pulmonary Disease - Internal Medici",
                                     "Pulmonary Diseases",
                                     "Radiological Physics",
                                     "Radiology",
                                     "Radiology Oncology",
                                     "Registered Nurse - Assistant",
                                     "Rehabilitation Medicine",
                                     "Reproductive Endocrinology",
                                     "Reproductive Endocrinology/Infertil",
                                     "Rheumatology - Internal Medicine",
                                     "School Nurse Practitioner",
                                     "Selective Pathology",
                                     "Sleep Medicine",
                                     "Sleep Medicine - Internal Medicine",
                                     "Sleep Medicine - Other",
                                     "Sleep Medicine - Pediatrics",
                                     "Social Worker - Behavioral Health",
                                     "Spinal Cord Injury (Physical Medici",
                                     "Sports Medicine - Pediatrics",
                                     "Sports Medicine - Physical Medicine",
                                     "Sports Medicine - Podiatry",
                                     "Student",
                                     "Surgery - Advanced Practice Registe",
                                     "Surgery - Assistant",
                                     "Surgery - Physician Assistant",
                                     "Surgery - Registered Nurse",
                                     "Surgery,Hand Surgery",
                                     "Surgical Oncology",
                                     "Technician",
                                     "Therapeutic Radiology",
                                     "Thoracic And Cardiac Surgery",
                                     "Thoracic Surgery",
                                     "Transplant Hepatology",
                                     "Transplant Surgery",
                                     "Transplant Surgery - Advanced Pract",
                                     "Trauma Surgery",
                                     "Undersea Medicine",
                                     "Urgent Care Medicine",
                                     "Urological Surgery",
                                     "Urology",
                                     "Urology - Registered Nurse",
                                     "Vascular And Interventional Radiolo",
                                     "Vascular Neurology - Neurology",
                                     "Vascular Surgery",
                                     "Veterinary"]
        return specialtyList
    }
    
    
}
